observatorium/observatorium

environments/openshift/main.jsonnet, environments/openshift/manifests/thanos-template.yaml, jsonnetfile.json, jsonnetfile.lock.json
=> Use strings for replicas in OpenShift template

build_deploy.sh
(see the comment in the script itself)
=> Add build_deploy.sh

environments/kubernetes/manifests/thanos-receive-service.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet.yaml, environments/kubernetes/manifests/thanos-store-service.yaml, environments/kubernetes/telemeter.libsonnet, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
cc @metalmatze @aditya-konarde @kakkoyun
=> *: bump kube-thanos

environments/kubernetes/manifests/thanos-receive-statefulSet.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
=> Update kube-thanos to remove empty volumeClaims

components/thanos-receive-controller.libsonnet, environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/main.jsonnet, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-controller-configmap.yaml, environments/kubernetes/manifests/thanos-receive-controller-deployment.yaml, environments/kubernetes/manifests/thanos-receive-controller-role.yaml, environments/kubernetes/manifests/thanos-receive-controller-roleBinding.yaml, environments/kubernetes/manifests/thanos-receive-controller-service.yaml, environments/kubernetes/manifests/thanos-receive-controller-serviceAccount.yaml, environments/kubernetes/manifests/thanos-receive-service.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml, tenants.libsonnet
Add the thanos-receive-controller to operator the current thanos-receive statefulset with a catch-all tenancy.
/cc @squat @kakkoyun @aditya-konarde @brancz
=> Add the thanos-receive-controller with a catch all tenancy

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-receive-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml
Let's try not to send things to the node itself. 
/cc @squat @aditya-konarde
=> Add --local-endpoint flag to receive component to prevent loops

README.md
=> README: add basic readme

environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml
cc @aditya-konarde @metalmatze
=> environments/openshift: disable htpasswd auth

environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
add metrics for CNV: 
* https://github.com/openshift/telemeter/pull/194
* https://github.com/openshift/telemeter/pull/195
and remove stale metrics:
* https://github.com/openshift/telemeter/pull/197
* https://github.com/openshift/telemeter/pull/198
cc @metalmatze @aditya-konarde @brancz
=> jsonnet: bump telemeter whitelist

environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml
cc @metalmatze @aditya-konarde
=> environemtns/openshift: remove observatorium from role

environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
This commit bumps the dependency on Telemeter to include the new metrics
introduced by:
* https://github.com/openshift/telemeter/pull/205
* https://github.com/openshift/telemeter/pull/192
@kakkoyun @metalmatze @aditya-konarde
=> jsonnet: bump telemeter and add new metrics

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/openshift/manifests/observatorium-template.yaml
=> environments: fix statefulset servicename

environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
This commit bumps telemeter to include the newly added metrics in
https://github.com/openshift/telemeter/pull/209.
cc @metalmatze @aditya-konarde @kakkoyun
=> jsonnet: bump telemeter

components/thanos-receive-controller.libsonnet, environments/kubernetes/manifests/thanos-receive-controller-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml
cc @metalmatze @kakkoyun @aditya-konarde
=> components: bump thanos-receive-controller

environments/kubernetes/manifests/telemeter-secret.yaml, environments/kubernetes/manifests/telemeter-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
cc @metalmatze @kakkoyun @aditya-konarde update telemeter-server credentials. stop using username so we can use new client credentials grant flow.
=> environments: bump telemeter

environments/sre/servicemonitors.jsonnet, environments/sre/servicemonitors/observatorium-thanos-receive-controller-production.servicemonitor.yaml, environments/sre/servicemonitors/observatorium-thanos-receive-controller-stage.servicemonitor.yaml
=> Add service monitors for Thanos receive controller

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/telemeter-statefulSet.yaml, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/kubernetes/telemeter.libsonnet
Update images to more recent versions.
=> Update Telemeter and Thanos images

environments/kubernetes/manifests/telemeter-secret.yaml, environments/kubernetes/manifests/telemeter-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
xref: https://github.com/openshift/telemeter/pull/224
cc @kakkoyun @aditya-konarde @metalmatze
=> environments: update telemeter secret

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
We want to save locally on a PVC the data that the Thanos Store gets from object storage.
/cc @kakkoyun @squat @aditya-konarde @brancz
=> Add a PVC to Thanos Store

.gitignore, environments/sre/grafana.jsonnet, environments/sre/grafana/grafana-dashboard-observatorium-thanos-compact.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-overview.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-querier.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-receive-controller.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-receive.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-rule.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-sidecar.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-store.configmap.yaml, environments/sre/prometheusrules.jsonnet, environments/sre/prometheusrules/observatorium-thanos-production.prometheusrules.yaml, environments/sre/prometheusrules/observatorium-thanos-stage.prometheusrules.yaml, jsonnetfile.json, jsonnetfile.lock.json
This PR;
* adds new alerts and dashboards for Thanos Receive Controller,
* updates error panels for Thanos dashboards,
* improves existing alerts
cc @metalmatze @squat @aditya-konarde
=> Add alerts and dashboards for Thanos receive controller

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/main.jsonnet, environments/kubernetes/manifests/thanos-compactor-service.yaml, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
We want to add the Thanos compactor to our stack to compact all the blocks that we already have in object storage as well as future ones.
/cc @squat @kakkoyun @bwplotka @brancz
=> Add Thanos compactor to Kubernetes and OpenShift

environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
=> Bump kube-thanos to introduce emptyDir for compactor

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml
=> Set missing data-dir for compactor and ignore malformed index for now

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml
=> Fix flag for compactor accept-malformed-index

environments/sre/servicemonitors.jsonnet, environments/sre/servicemonitors/observatorium-thanos-compactor-production.servicemonitor.yaml, environments/sre/servicemonitors/observatorium-thanos-compactor-stage.servicemonitor.yaml, jsonnetfile.lock.json
We want to monitor the Thanos compactor too.
/cc @aditya-konarde @kakkoyun @squat
=> environments/sre: Add ServiceMonitors for thanos compactor

environments/sre/grafana/grafana-dashboard-observatorium-thanos-overview.configmap.yaml, environments/sre/grafana/grafana-dashboard-observatorium-thanos-receive.configmap.yaml, environments/sre/prometheusrules/observatorium-thanos-production.prometheusrules.yaml, environments/sre/prometheusrules/observatorium-thanos-stage.prometheusrules.yaml, jsonnetfile.lock.json
cc @squat @metalmatze @bwplotka
=> Update Thanos Alerts and Dashboards

environments/sre/prometheusrules.jsonnet, environments/sre/prometheusrules/observatorium-thanos-production.prometheusrules.yaml, environments/sre/prometheusrules/observatorium-thanos-stage.prometheusrules.yaml, jsonnetfile.lock.json
This PR,
* Adds alerts  for compactor
* Updates selector for alerts, as in #66, to select multiple deployments of components.
=> Update selectors, add compactor alerts

environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
Follow up to https://github.com/openshift/telemeter/pull/235
cc @kakkoyun @metalmatze
=> Bug 1749451: Add node_role_os_version_machine:cpu_capacity_cores:sum

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml
As discussed in previous meetings.
/cc @brancz @kakkoyun @squat
=> Update retention to be 32d,92d,0d

environments/kubernetes/manifests/telemeter-statefulSet.yaml, environments/kubernetes/telemeter.libsonnet
Bump to deploy:
* https://github.com/openshift/telemeter/pull/243
* https://github.com/openshift/telemeter/pull/242
@metalmatze @ant31 @squat @kakkoyun @aditya-konarde
=> telemeter-server: Bump to include type and encoding fix

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/prometheus.libsonnet
=> Disable Prometheus AMS debug logs and remove configured remote-write timeout

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/prometheus.libsonnet, environments/sre/servicemonitors/observatorium-prometheus-ams-production.servicemonitor.yaml, environments/sre/servicemonitors/observatorium-prometheus-ams-stage.servicemonitor.yaml
=> Use Kubernetes recommended labels for Prometheus AMS

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml
=> Use individual hashring service for Thanos querirer Service Discovery

environments/sre/prometheusrules/observatorium-thanos-production.prometheusrules.yaml, environments/sre/prometheusrules/observatorium-thanos-stage.prometheusrules.yaml, jsonnetfile.lock.json
=> Update Observatorium alerts

environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml, environments/sre/prometheusrules/observatorium-thanos-production.prometheusrules.yaml, environments/sre/prometheusrules/observatorium-thanos-stage.prometheusrules.yaml, jsonnetfile.lock.json
This PR,
* updates Thanos to [latest stable version](https://github.com/thanos-io/thanos/releases)
* updates Thanos Receive Controller to [latest version](https://quay.io/repository/observatorium/thanos-receive-controller?tab=tags)
cc @aditya-konarde @brancz @bwplotka
=> Update dependencies to reflect upstream changes

environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
cc @aditya-konarde @metalmatze
=> Fix issue with renamed receive flag

environments/sre/prometheusrules.jsonnet, environments/sre/prometheusrules/observatorium-thanos-production.prometheusrules.yaml, environments/sre/prometheusrules/observatorium-thanos-stage.prometheusrules.yaml, jsonnetfile.lock.json
cc @squat @metalmatze @brancz @bwplotka
=> Add absent alerts for Thanos components

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
This PR,
* upgrades kube-thanos to the latest version
* remove liveness probes
cc @squat @brancz @bwplotka @aditya-konarde
=> Remove liveness probes

environments/openshift/jaeger.jsonnet, environments/openshift/manifests/jaeger-template.yaml
=> Jaeger replicas parameter in OpenShift template is a string

components/jaeger-collector.libsonnet, environments/kubernetes/manifests/jaeger-deployment.yaml, environments/openshift/manifests/jaeger-template.yaml
=> Jaeger probe ports should be ints

environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
/cc @aditya-konarde @squat @kakkoyun
=> Fix the Thanos Receive volumemounts with PVCs

components/jaeger-collector.libsonnet, environments/openshift/jaeger.jsonnet, environments/openshift/manifests/jaeger-template.yaml
=> openshift/jaeger: Use gp2-encrypted as storageclass

environments/sre/prometheusrules.jsonnet, environments/sre/prometheusrules/observatorium-thanos-production.prometheusrules.yaml, environments/sre/prometheusrules/observatorium-thanos-stage.prometheusrules.yaml, jsonnetfile.json, jsonnetfile.lock.json
=> Generate absent alert per tenant

environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
Follow up to https://github.com/openshift/telemeter/pull/255
cc @kakkoyun @metalmatze
=> Bug 1760393: Add node_role_os_version_machine:cpu_capacity_sockets:sum

components/jaeger-agent.libsonnet, environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml
Most reviewers are probably interested in all .yaml files. 
The store container is currently missing the `--tracing.config` flag which needs to be added before merging this PR.
However for a general review this is good to go from my side.
/cc @jpkrohling @bwplotka @brancz @kakkoyun @squat
=> Add Jaeger Agent as sidecar

components/jaeger-collector.libsonnet, environments/kubernetes/manifests/jaeger-deployment.yaml, environments/openshift/manifests/jaeger-template.yaml
As we only have one PVC we want to scale down this deployment entirely before running another pod with the PVC
/cc @aditya-konarde @brancz
=> Add maxSurge=0 and maxUnavailable=1 to scale down jaeger before deploying

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Added missing jaeger flag to Thanos store.

environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Fixed default args for kube-thanos.

environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
Picks up https://github.com/openshift/telemeter/pull/263
=> jsonnetfile: Bump to newer telemeter for virt_platform_type

components/jaeger-agent.libsonnet, environments/kubernetes/kube-thanos.libsonnet, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/observatorium-template.yaml
Add parameters for OpenShift template for the Jaeger Agent images.
/cc @aditya-konarde
=> Create OpenShift template parameter for Jaeger agent

environments/openshift/jaeger.jsonnet, environments/openshift/manifests/jaeger-template.yaml, fmt.sh
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Added limits and resources to the JAEGER proxy as it's required now.

environments/openshift/jaeger.jsonnet, environments/openshift/kube-thanos.libsonnet, environments/openshift/manifests/jaeger-template.yaml, environments/openshift/manifests/observatorium-template.yaml
Signed-off-by: Bartek Plotka <bwplotka@gmail.com>
=> Added req & limits to jaeger proxy in Thanos as well.

components/thanos-querier-cache.libsonnet, environments/kubernetes/manifests/thanos-querier-cache-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml
Let's disable the ServiceLinks in Cortex cache.
/cc @aditya-konarde @brancz @kakkoyun
=> Disable ServiceLinks for Cortex cache

components/thanos-querier-cache.libsonnet, environments/kubernetes/manifests/thanos-querier-cache-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml
/cc @aditya-konarde @squat @brancz
=> Run 3 replicas of the cortex cache frontend

environments/kubernetes/manifests/telemeter-memcached-service.yaml, environments/kubernetes/manifests/telemeter-memcached-serviceMonitor.yaml, environments/kubernetes/manifests/telemeter-memcached-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/telemeter-template.yaml, environments/openshift/telemeter.jsonnet, environments/sre/servicemonitors.jsonnet, environments/sre/servicemonitors/telemeter-memcached-stage.servicemonitor.yaml, environments/sre/servicemonitors/telemeter-memcached.servicemonitor.yaml, jsonnetfile.lock.json
=> environments: add memcached monitoring

environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, environments/openshift/thanos.jsonnet, jsonnetfile.json, jsonnetfile.lock.json
This PR adds similar changes as in https://github.com/thanos-io/kube-thanos/pull/65, since Observatorium runs master version of Thanos.
=> Add termination grace period to Thanos pods

environments/kubernetes/manifests/thanos-ruler-service.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, jsonnetfile.lock.json
=> Upgrade kube-thanos to use ruler headless service

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, environments/openshift/thanos.jsonnet, jsonnetfile.lock.json
=> Add first telemeter rules to Observatorium

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, environments/openshift/thanos.jsonnet
😅 
cc @aditya-konarde  @metalmatze  @squat
=> Add forgotten volume for Telemeter rules configmap

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, environments/openshift/thanos.jsonnet
This fixes issues that are introduced in #145, #146
* mismatching volume names,
* removes items from volumes.
cc @squat @metalmatze
=> Fix Thanos Ruler rule file mount issues

environments/kubernetes/manifests/thanos-ruler-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, jsonnetfile.lock.json
cc @squat @metalmatze @bwplotka 
xref: https://github.com/thanos-io/kube-thanos/pull/80
=> Fix Thanos Ruler Query API service discovery issue

environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, jsonnetfile.lock.json
=> Update kube-thanos to get anti-affinity for queriers and receivers

components/thanos-querier-cache.libsonnet, environments/kubernetes/main.jsonnet, environments/kubernetes/observatorium.libsonnet, environments/openshift/manifests/observatorium-api-template.yaml, environments/openshift/observatorium-api.jsonnet
=> Fix namespace issues with service DNS

environments/openshift/manifests/observatorium-api-template.yaml, environments/openshift/observatorium-api.jsonnet
=> Add required image tag parameters

environments/openshift/jaeger.jsonnet, environments/openshift/manifests/observatorium-api-template.yaml, environments/openshift/observatorium.libsonnet
=> Fix parameter conversion issue

environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/kubernetes/manifests/thanos-ruler-statefulSet.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, jsonnetfile.lock.json
=> Reduce interval for readiness probes

environments/kubernetes/main.jsonnet, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/manifests/thanos-template.yaml, environments/openshift/thanos.jsonnet
This PR adds left-over changes from #163.
=> Update external prefix for OpenShift configuration

.circleci/config.yml, .gitignore, environments/kubernetes/kube-thanos.libsonnet, environments/kubernetes/manifests/observatorium-api-deployment.yaml, environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml, environments/kubernetes/manifests/thanos-querier-deployment.yaml, environments/kubernetes/manifests/thanos-receive-controller-deployment.yaml, environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml, environments/kubernetes/manifests/thanos-ruler-statefulSet.yaml, environments/kubernetes/manifests/thanos-store-statefulSet.yaml, environments/testing/minio.yaml, environments/testing/secret.yaml, jsonnetfile.json, jsonnetfile.lock.json, tests/deploy.sh, tests/kind.sh, tests/manifests/observatorium-up.yaml, tests/test.sh
=> Use CircleCI and run KinD clusters there for e2e tests

environments/testing/secret.yaml
As per discussion in #72 we want to use stringData in the testing secret for object storage :)
/cc @brancz @squat
=> Use stringData in testing objectstorage secret

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
@squat @kakkoyun @metalmatze @bwplotka @krasi-georgiev
=> environments/openshift: Remove replicas from compact resources

components/oauth-proxy.libsonnet, environments/openshift/manifests/observatorium-template.yaml
@metalmatze @squat @bwplotka @kakkoyun @krasi-georgiev
=> environments/openshift: Set correct ServiceAccount

components/jaeger-agent.libsonnet, environments/openshift/manifests/observatorium-template.yaml
@squat @metalmatze @kakkoyun @bwplotka @krasi-georgiev
=> environments/openshift: Add resource requests and limit to jaeger-agent

environments/openshift/thanos-alerts.libsonnet
/cc @brancz @aditya-konarde @kakkoyun
=> Update the job selector for thanos-receive-controller

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
@kakkoyun @metalmatze @bwplotka @krasi-georgiev @squat
=> environments/openshift: Fix rule mounts

environments/base/default-config.libsonnet, environments/base/manifests/thanos-compact-service.yaml, environments/base/manifests/thanos-compact-statefulSet.yaml, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-query-service.yaml, environments/base/manifests/thanos-receive-default-service.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/base/manifests/thanos-rule-service.yaml, environments/base/manifests/thanos-rule-statefulSet.yaml, environments/base/manifests/thanos-store-service.yaml, environments/base/manifests/thanos-store-statefulSet.yaml, environments/dev/manifests/thanos-compact-service.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-query-service.yaml, environments/dev/manifests/thanos-receive-default-service.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-rule-service.yaml, environments/dev/manifests/thanos-rule-statefulSet.yaml, environments/dev/manifests/thanos-store-service.yaml, environments/dev/manifests/thanos-store-statefulSet.yaml
In preparation for a prod rollout, let's test this version here already.
@squat @metalmatze @kakkoyun @bwplotka @krasi-georgiev
=> environments/base: Bump to thanos v0.10.1

environments/base/manifests/thanos-store-statefulSet.yaml, environments/dev/manifests/thanos-store-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
The v0.10.1 version currently used here does not have the binary index
header feater/flag yet.
@bwplotka @metalmatze @squat @kakkoyun @krasi-georgiev
=> *: Remove binary index header flag

environments/base/manifests/thanos-store-statefulSet.yaml, environments/dev/manifests/thanos-store-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
@kakkoyun @metalmatze @squat @bwplotka @krasi-georgiev
=> *: Enable store binary index header feature

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Bump obs Thanos version to v0.11.0-rc.0

components/observatorium-configure.libsonnet, components/observatorium.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-store-shard0-service.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-store-shard0-service.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
I left everything at 1 shard for the base and dev environment but 3 shards for the prod env.
@bwplotka @squat @metalmatze @kakkoyun @krasi-georgiev
=> *: Introduce store sharding

components/observatorium.libsonnet, environments/base/manifests/thanos-store-shard0-service.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/thanos-store-shard0-service.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml
This way each store shard's service will actually only select its shard.
@metalmatze @squat @bwplotka @krasi-georgiev @kakkoyun
=> *: Label store shard objects appropriately

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
@aditya-konarde @bwplotka @metalmatze @kakkoyun @krasi-georgiev @squat
=> environments/openshift: Make storage class configurable

environments/base/manifests/thanos-compact-statefulSet.yaml, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/base/manifests/thanos-rule-statefulSet.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-rule-statefulSet.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
Just some updates that I happened to do for other reasons.
@squat @metalmatze @kakkoyun @bwplotka @krasi-georgiev
=> *: Update dependencies

components/observatorium.libsonnet, environments/base/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml
Due to the recent renaming of the Ruler to Rule we also need to start
dedupping both names...
/cc @brancz @squat
=> Add rule_replica to replicaLabels

components/observatorium.libsonnet, environments/base/manifests/api-gateway-thanos-query-deployment.yaml, environments/dev/manifests/api-gateway-thanos-query-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml, jsonnetfile.lock.json
As this Querier is just for the UI assets we don't need these store and replica-labels setup.
/cc @kakkoyun @squat @rollandf
=> Set store and replica-label flag on API Gateway to empty

components/cortex-query-frontend.libsonnet, environments/base/manifests/query-cache-deployment.yaml, environments/dev/manifests/query-cache-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
@metalmatze @squat @krasi-georgiev @aditya-konarde
=> environments/openshift: Disable cache retries and use latest version

components/cortex-query-frontend.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/query-cache-configmap.yaml, environments/base/manifests/query-cache-deployment.yaml, environments/base/manifests/query-cache-service.yaml, environments/dev/manifests/query-cache-configmap.yaml, environments/dev/manifests/query-cache-deployment.yaml, environments/dev/manifests/query-cache-service.yaml, environments/openshift/manifests/observatorium-template.yaml
A case of "how did this ever work?" :thinking: I think cortex didn't use to strictly parse the config.
@metalmatze @squat @krasi-georgiev
=> *: Fix query cache config

components/observatorium.libsonnet, environments/base/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/openshift/manifests/observatorium-template.yaml
@metalmatze @squat @aditya-konarde
=> Remove `ruler_replica` as no data is available anymore with this label

example/core_v1alpha1_observatorium.yaml
=> Update example to use cortex image master-fdcd992f

components/observatorium.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/api-gateway-deployment.yaml, environments/base/manifests/api-gateway-service.yaml, environments/dev/manifests/api-gateway-deployment.yaml, environments/dev/manifests/api-gateway-service.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet, example/core_v1alpha1_observatorium.yaml, jsonnetfile.lock.json, tests/main.jsonnet, tests/manifests/observatorium-up.yaml
Upgrade Observatorium API GW to its latest version
cc @nmagnezi
=> Upgrade Observatorium API GW

.circleci/config.yml, jsonnetfile.json, jsonnetfile.lock.json
=> Upgrade jsonnet-bundler

environments/base/default-config.libsonnet, environments/base/manifests/api-gateway-thanos-query-deployment.yaml, environments/base/manifests/api-gateway-thanos-query-service.yaml, environments/base/manifests/thanos-compact-service.yaml, environments/base/manifests/thanos-compact-statefulSet.yaml, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-query-service.yaml, environments/base/manifests/thanos-receive-default-service.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/base/manifests/thanos-rule-service.yaml, environments/base/manifests/thanos-rule-statefulSet.yaml, environments/base/manifests/thanos-store-shard0-service.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/api-gateway-thanos-query-deployment.yaml, environments/dev/manifests/api-gateway-thanos-query-service.yaml, environments/dev/manifests/thanos-compact-service.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-query-service.yaml, environments/dev/manifests/thanos-receive-default-service.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-rule-service.yaml, environments/dev/manifests/thanos-rule-statefulSet.yaml, environments/dev/manifests/thanos-store-shard0-service.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, example/manifests/observatorium.yaml
Upgrade to [the latest Thanos version](https://quay.io/repository/thanos/thanos/manifest/sha256:49275de06d3bed2729dbe8a8fa34bc5307151c979cc54b75c004d3f987424cd6) bed5536a435535c6a75db63f68f61093e6e99813
=> Upgrade Thanos to the latest version

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
OAuth proxy is needed to use Thanos compactor UI
=> Add OAuth proxy for thanos compactor

tests/main.jsonnet, tests/manifests/observatorium-up.yaml
Based on:
https://github.com/observatorium/observatorium/blob/master/test/integration.sh#L43
=> Update UP Read URL

components/oauth-proxy.libsonnet, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
Fix for previously introduce bug #223
=> Introduce OAuth proxy mixins

components/minio.libsonnet, environments/dev/main.jsonnet, environments/dev/manifests/minio-deployment.yaml, environments/dev/manifests/minio-pvc.yaml, environments/dev/manifests/minio-secret.yaml, environments/dev/manifests/minio-service.yaml, tests/e2e.sh
=> Create minio resources in a seperate namespace

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
@kakkoyun @metalmatze @squat @bwplotka @krasi-georgiev
=> environments/openshift: Fix up read endpoint port

components/cortex-query-frontend.libsonnet, components/up.libsonnet
=> components/*: Remove app version labels from ServiceMonitor selectors

components/observatorium-configure.libsonnet, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
Refactor up generation, so the configuration is reusable when importing
it as a dependency.
@kakkoyun @metalmatze
=> environment/openshift: Refactor up generation

environments/openshift/kube-telemeter.libsonnet, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet, environments/openshift/telemeter.jsonnet, jsonnetfile.lock.json
Continuation of #180.
Let's wait until next week to merge this, but this should now do the trick I believe.
@kakkoyun @squat @bwplotka @metalmatze @krasi-georgiev 
cc @maorfr
=> use authorize-url from Secret - continuation of #180

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
- Remove unused jaeger-agent
- Add PVC for compactor
=> thanos/compactor: Add PVC, remove jaeger

environments/base/default-config.libsonnet, tests/main.jsonnet, tests/manifests/observatorium-up.yaml
This commit bumps the version of up.
Fixes: #221
=> environments,test: bump up

environments/openshift/kube-telemeter.libsonnet, environments/openshift/manifests/observatorium-template.yaml
PR that added this incluster https://github.com/openshift/cluster-monitoring-operator/pull/660
cc @brancz @metalmatze
=> environments/openshift/kube-telemeter.libsonnet: Extend limit-bytes

jsonnetfile.json, jsonnetfile.lock.json
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>
=> fix the mixin/thanos import path

environments/base/default-config.libsonnet, environments/base/manifests/api-gateway-thanos-query-deployment.yaml, environments/base/manifests/api-gateway-thanos-query-service.yaml, environments/base/manifests/thanos-compact-service.yaml, environments/base/manifests/thanos-compact-statefulSet.yaml, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-query-service.yaml, environments/base/manifests/thanos-receive-default-service.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/base/manifests/thanos-rule-service.yaml, environments/base/manifests/thanos-rule-statefulSet.yaml, environments/base/manifests/thanos-store-shard0-service.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/api-gateway-thanos-query-deployment.yaml, environments/dev/manifests/api-gateway-thanos-query-service.yaml, environments/dev/manifests/thanos-compact-service.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-query-service.yaml, environments/dev/manifests/thanos-receive-default-service.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-rule-service.yaml, environments/dev/manifests/thanos-rule-statefulSet.yaml, environments/dev/manifests/thanos-store-shard0-service.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet, example/manifests/observatorium.yaml, jsonnetfile.lock.json
* Upgrade Thanos v0.12.0-rc.1
* Upgrade kube-thanos version
=> Upgrade to Thanos v0.12.0-rc.1 and compatible kube-thanos version

environments/openshift/manifests/observatorium-template.yaml, environments/openshift/obs.jsonnet
I hope receiver version change is ok... it was bit old for a reason?
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> thanos: Bump to v0.12.0.

components/up.libsonnet
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>
=> Allow write for the up tool for deployments

.circleci/config.yml, environments/operator/obs-operator.jsonnet, environments/operator/operator-config.libsonnet, tests/e2e.sh
Fixes: #235
Co-authored-by: Fred Rolland <frolland@redhat.com>
=> Add ownerReferences for resources created by CR

components/observatorium.libsonnet, deploy/crds/core.observatorium.io_observatoria.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml
=> receive: Increase local retention to 15 days

Dockerfile, deploy/crds/core.observatorium.io_observatoria.yaml, operator/api/v1alpha1/observatorium_types.go, operator/jsonnet/operator-config.libsonnet
=>  Use defaults for images in operator

Makefile, components/observatorium.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/thanos-compact-service.yaml, environments/base/manifests/thanos-compact-statefulSet.yaml, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-query-service.yaml, environments/base/manifests/thanos-receive-default-service.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/base/manifests/thanos-rule-service.yaml, environments/base/manifests/thanos-rule-statefulSet.yaml, environments/base/manifests/thanos-store-shard0-service.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/thanos-compact-service.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-query-service.yaml, environments/dev/manifests/thanos-receive-default-service.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-rule-service.yaml, environments/dev/manifests/thanos-rule-statefulSet.yaml, environments/dev/manifests/thanos-store-shard0-service.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, example/manifests/observatorium.yaml, operator/jsonnet/jsonnetfile.lock.json, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-store.libsonnet
depends: https://github.com/observatorium/configuration/pull/279
=> Enable Thanos Store with caching bucket

components/observatorium.libsonnet, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, operator/jsonnet/jsonnetfile.lock.json, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-query.libsonnet
=> *: Increase query timeout to 15m

components/cortex-query-frontend.libsonnet
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>
=> add commonLabels to the cortex querier

components/observatorium.libsonnet, environments/base/manifests/api-deployment.yaml, operator/api/v1alpha1/observatorium_types.go, operator/jsonnet/operator-config.libsonnet, operator/manifests/crds/core.observatorium.io_observatoria.yaml
Fixes: https://github.com/observatorium/deployments/issues/314
=> Make loki is optional

components/observatorium.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/thanos-compact-statefulSet.yaml, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/base/manifests/thanos-rule-statefulSet.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-rule-statefulSet.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, operator/jsonnet/jsonnetfile.lock.json, operator/jsonnet/operator-config.libsonnet, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-bucket.libsonnet, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-compact.libsonnet, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-query.libsonnet, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-receive.libsonnet, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-rule.libsonnet, operator/jsonnet/vendor/github.com/thanos-io/kube-thanos/jsonnet/kube-thanos/kube-thanos-store.libsonnet
* Add ability to change the log level https://github.com/thanos-io/kube-thanos/pull/143
* Only perform anti-affinity against receive pods https://github.com/thanos-io/kube-thanos/pull/134
=> thanos *: Upgrade to latest kube-thanos

components/observatorium.libsonnet
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Almost the same as https://github.com/thanos-io/kube-thanos/pull/144.
=> Specify downstreamURL port from query service

components/observatorium.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, example/main.jsonnet, example/manifests/observatorium.yaml, operator/api/v1alpha1/observatorium_types.go, operator/jsonnet/obs-operator.jsonnet, operator/manifests/crds/core.observatorium.io_observatoria.yaml
=> Configure enable/disable downsampling

README.md
Operator moved to https://github.com/observatorium/operator
=> Remove Operator information from README.md

jsonnetfile.json, jsonnetfile.lock.json
=> Remove unused dependency

tests/e2e.sh
=> e2e: Clean test script

components/gubernator.libsonnet, components/observatorium-configure.libsonnet, components/observatorium.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/api-deployment.yaml, environments/base/manifests/api-service.yaml, environments/base/manifests/api-serviceAccount.yaml, environments/base/manifests/gubernator-deployment.yaml, environments/base/manifests/gubernator-role.yaml, environments/base/manifests/gubernator-roleBinding.yaml, environments/base/manifests/gubernator-service.yaml, environments/base/manifests/gubernator-serviceAccount.yaml, environments/dev/main.jsonnet, environments/dev/manifests/api-configmap.yaml, environments/dev/manifests/api-deployment.yaml, environments/dev/manifests/api-secret.yaml, environments/dev/manifests/api-service.yaml, environments/dev/manifests/api-serviceAccount.yaml, environments/dev/manifests/gubernator-deployment.yaml, environments/dev/manifests/gubernator-role.yaml, environments/dev/manifests/gubernator-roleBinding.yaml, environments/dev/manifests/gubernator-service.yaml, environments/dev/manifests/gubernator-serviceAccount.yaml, jsonnetfile.json, jsonnetfile.lock.json, tests/e2e.sh
This PR add manifests to deploy rate-limiting per tenant.
Depends xref: https://github.com/observatorium/observatorium/pull/102
=> Add gubernator resource manifests

components/gubernator.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/api-deployment.yaml, environments/base/manifests/api-service.yaml, environments/base/manifests/api-serviceAccount.yaml, environments/base/manifests/gubernator-deployment.yaml, environments/base/manifests/gubernator-role.yaml, environments/base/manifests/gubernator-roleBinding.yaml, environments/base/manifests/gubernator-service.yaml, environments/base/manifests/gubernator-serviceAccount.yaml, environments/dev/manifests/api-configmap.yaml, environments/dev/manifests/api-deployment.yaml, environments/dev/manifests/api-secret.yaml, environments/dev/manifests/api-service.yaml, environments/dev/manifests/api-serviceAccount.yaml, environments/dev/manifests/gubernator-deployment.yaml, environments/dev/manifests/gubernator-role.yaml, environments/dev/manifests/gubernator-roleBinding.yaml, environments/dev/manifests/gubernator-service.yaml, environments/dev/manifests/gubernator-serviceAccount.yaml
Blocking issue has been fixed
xref: https://github.com/mailgun/gubernator/issues/50
=> gubernator: Do not use privileged ports

components/observatorium.libsonnet, environments/base/default-config.libsonnet, environments/base/manifests/thanos-compact-service.yaml, environments/base/manifests/thanos-compact-statefulSet.yaml, environments/base/manifests/thanos-query-deployment.yaml, environments/base/manifests/thanos-query-frontend-deployment.yaml, environments/base/manifests/thanos-query-frontend-service.yaml, environments/base/manifests/thanos-query-frontend-serviceMonitor.yaml, environments/base/manifests/thanos-query-service.yaml, environments/base/manifests/thanos-receive-default-service.yaml, environments/base/manifests/thanos-receive-default-statefulSet.yaml, environments/base/manifests/thanos-rule-service.yaml, environments/base/manifests/thanos-rule-statefulSet.yaml, environments/base/manifests/thanos-store-shard0-service.yaml, environments/base/manifests/thanos-store-shard0-statefulSet.yaml, environments/dev/manifests/thanos-compact-service.yaml, environments/dev/manifests/thanos-compact-statefulSet.yaml, environments/dev/manifests/thanos-query-deployment.yaml, environments/dev/manifests/thanos-query-frontend-deployment.yaml, environments/dev/manifests/thanos-query-frontend-service.yaml, environments/dev/manifests/thanos-query-frontend-serviceMonitor.yaml, environments/dev/manifests/thanos-query-service.yaml, environments/dev/manifests/thanos-receive-default-service.yaml, environments/dev/manifests/thanos-receive-default-statefulSet.yaml, environments/dev/manifests/thanos-rule-service.yaml, environments/dev/manifests/thanos-rule-statefulSet.yaml, environments/dev/manifests/thanos-store-shard0-service.yaml, environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, jsonnetfile.json, jsonnetfile.lock.json
Refactoring to use functions that kube-thanos exposes going forward.
=> Start using functions of kube-thanos

components/observatorium.libsonnet, jsonnetfile.lock.json
=> Upgrade thanos receive controller

components/thanos.libsonnet
=> Add missing configuration for operator

components/thanos.libsonnet, jsonnetfile.lock.json
dependes xref: https://github.com/thanos-io/kube-thanos/pull/170
=> thanos: Use upstream functions

components/loki.libsonnet, environments/base/manifests/loki-compactor-statefulset.yaml, environments/base/manifests/loki-distributor-deployment.yaml, environments/base/manifests/loki-ingester-statefulset.yaml, environments/base/manifests/loki-querier-statefulset.yaml, environments/base/manifests/loki-query-frontend-deployment.yaml, environments/dev/manifests/loki-compactor-statefulset.yaml, environments/dev/manifests/loki-distributor-deployment.yaml, environments/dev/manifests/loki-ingester-statefulset.yaml, environments/dev/manifests/loki-querier-statefulset.yaml, environments/dev/manifests/loki-query-frontend-deployment.yaml
This PR adds simple but tolerant liveness probes for Loki components in the absence of more fine-grained liveness signals.
=> [loki] Add simple livenessProbes

components/observatorium.libsonnet
Signed-off-by: clyang82 <chuyang@redhat.com>
=> Make loki as optional component

components/thanos.libsonnet, environments/base/manifests/thanos-store-service-account.yaml, environments/dev/manifests/thanos-store-service-account.yaml, environments/local/manifests/thanos-store-service-account.yaml
Follow up for #383. I missed to actually render the store ServiceAccount.
@kakkoyun
=> components/thanos: Correctly render store ServiceAccount

components/thanos.libsonnet, environments/base/manifests/thanos-store-service-account.yaml, environments/dev/manifests/thanos-store-service-account.yaml, environments/local/manifests/thanos-store-service-account.yaml
Yet-another-but-finally-correct fix. :D 
I guess it's time to stop working for today...
@kakkoyun
=> components/thanos: Fix store ServiceAccount mix-up

components/thanos.libsonnet
=> Allow piping through all configuration and configuring all ServiceMonitors

components/memcached.libsonnet, environments/base/manifests/thanos-query-frontend-cache-serviceAccount.yaml, environments/base/manifests/thanos-query-frontend-cache-statefulSet.yaml, environments/base/manifests/thanos-store-cache-serviceAccount.yaml, environments/base/manifests/thanos-store-cache-statefulSet.yaml, environments/dev/manifests/thanos-query-frontend-cache-serviceAccount.yaml, environments/dev/manifests/thanos-query-frontend-cache-statefulSet.yaml, environments/dev/manifests/thanos-store-cache-serviceAccount.yaml, environments/dev/manifests/thanos-store-cache-statefulSet.yaml, environments/local/manifests/thanos-query-frontend-cache-serviceAccount.yaml, environments/local/manifests/thanos-query-frontend-cache-statefulSet.yaml, environments/local/manifests/thanos-store-cache-serviceAccount.yaml, environments/local/manifests/thanos-store-cache-statefulSet.yaml
Tested on a cluster, and works beautifully :) 
@kakkoyun
=> components/memcached: Use non-root and own ServiceAccount

components/thanos.libsonnet
expose fields in conf, including `volumeClaimTemplate`, etc. in the past, we allow to configure `storageClassName` in `volumeClaimTemplate`. that is real case in production environment.
partial fix for https://github.com/observatorium/operator/issues/50
/assign @squat @kakkoyun 
Signed-off-by: clyang82 <chuyang@redhat.com>
=> expose fields

components/memcached.libsonnet, environments/base/manifests/thanos-query-frontend-cache-statefulSet.yaml, environments/base/manifests/thanos-store-cache-statefulSet.yaml, environments/dev/manifests/thanos-query-frontend-cache-statefulSet.yaml, environments/dev/manifests/thanos-store-cache-statefulSet.yaml, environments/local/manifests/thanos-query-frontend-cache-statefulSet.yaml, environments/local/manifests/thanos-store-cache-statefulSet.yaml
observatorium/operator#51
Signed-off-by: clyang82 <chuyang@redhat.com>
=> Make securityContext configurable

configuration/environments/base/manifests/thanos-compact-statefulSet.yaml, configuration/environments/base/manifests/thanos-query-deployment.yaml, configuration/environments/base/manifests/thanos-query-frontend-deployment.yaml, configuration/environments/base/manifests/thanos-receive-default-statefulSet.yaml, configuration/environments/base/manifests/thanos-rule-statefulSet.yaml, configuration/environments/base/manifests/thanos-store-shard0-service.yaml, configuration/environments/base/manifests/thanos-store-shard0-statefulSet.yaml, configuration/environments/dev/manifests/thanos-compact-statefulSet.yaml, configuration/environments/dev/manifests/thanos-query-deployment.yaml, configuration/environments/dev/manifests/thanos-query-frontend-deployment.yaml, configuration/environments/dev/manifests/thanos-receive-default-statefulSet.yaml, configuration/environments/dev/manifests/thanos-rule-statefulSet.yaml, configuration/environments/dev/manifests/thanos-store-shard0-service.yaml, configuration/environments/dev/manifests/thanos-store-shard0-statefulSet.yaml, configuration/environments/local/manifests/thanos-compact-statefulSet.yaml, configuration/environments/local/manifests/thanos-query-deployment.yaml, configuration/environments/local/manifests/thanos-query-frontend-deployment.yaml, configuration/environments/local/manifests/thanos-receive-default-statefulSet.yaml, configuration/environments/local/manifests/thanos-rule-statefulSet.yaml, configuration/environments/local/manifests/thanos-store-shard0-service.yaml, configuration/environments/local/manifests/thanos-store-shard0-statefulSet.yaml, configuration/jsonnetfile.lock.json
=> Upgrade kube-thanos

CODE_OF_CONDUCT.md, docs/community/_index.md, docs/community/governance.md, docs/community/maintainers.md, website/config/_default/menus.toml
As it's the introduction on formal governance, I will start official vote on internal mailing list.
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Propose Code of Conduct, Governance and Maintainers list.

docs/design/metrics.md
Fixes Thanos proposal link which got changed [here](https://github.com/thanos-io/thanos/pull/4339).
=> Fix proposal link

docs/proposals/20201019-prometheus-rules-in-observatorium-api.md
This PR updates the Rules API proposal to also accommodate alerting rules. I just reword the proposal and removed the "What if a user gives us an alerting rule" section.
=> Rules API proposal: Accommodate alerting rules

README.md, docs/community/README.md
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Added section about contributing.

docs/proposals/20201019-prometheus-rules-in-observatorium-api.md
Changing the title so it also conforms to https://github.com/observatorium/observatorium/pull/430
Signed-off-by: Jéssica Lins <jlins@redhat.com>
=> Rules API proposal: Fix title

docs/community/README.md
=> docs/community: clean up grammar

docs/usage/getting-started.md
Signed-off-by: Ed Snible <snible@us.ibm.com>
=> Fix Prometheus download instructions for MacOS

configuration/examples/local/quickstart.sh
This PR fixes the `quickstart.sh` script to work on macOS.
=> Fix `quickstart` script for macOS

docs/community/maintainers.md
This PR adds @matej-g to the Observatorium maintainers and updates the affiliations of existing maintainers.
=> Maintainer Updates

README.md, docs/design/architecture.md, docs/usage/getting-started.md
Signed-off-by: Ed Snible <snible@us.ibm.com>
=> Spell check

docs/usage/getting-started.md
Signed-off-by: Douglas Camata <159076+douglascamata@users.noreply.github.com>
Somehow this passed in #479
=> Fix getting started doc linting

configuration/components/tracing.libsonnet, configuration/examples/local/manifests/observatorium/tracing-otelcollector.yaml
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
=> Make OTELcol TLS configurable

configuration/examples/base/manifests/observatorium/api-service.yaml, configuration/examples/dev/manifests/observatorium/api-service.yaml, configuration/examples/local/manifests/observatorium/api-service.yaml, configuration/jsonnetfile.lock.json
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
=> Bump obs/api jsonnet to latest

configuration/components/tracing.libsonnet, configuration/examples/local/main.jsonnet
Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>
---
cc @esnible @pavolloffay
=> make jaegerSpec configurable and set index-prefix when needed

configuration/components/tracing.libsonnet, configuration/examples/local/main.jsonnet, configuration/examples/local/manifests/observatorium/tracing-jaeger-podmonitor-test-oidc.yaml, configuration/examples/local/manifests/observatorium/tracing-otelcollector.yaml, configuration/examples/local/manifests/observatorium/tracing-servicemonitor-otel.yaml
This PR superseded https://github.com/observatorium/observatorium/pull/494 which for some unknown reason got CI got stuck.
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
=> Add service monitor to tracing

docs/proposals/approved/20201019-prometheus-rules-in-observatorium-api.md
The real intention of this PR is to check if my account is having problems with CI. but also fixed a misspelling :) 
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
=> Fix spelling

docs/community/maintainers.md
Adding myself to maintainers, as instructed via email! ❤️
=> Add myself to maintainers

configuration/Makefile, configuration/components/loki.libsonnet
And removes `sed` dependency in favor of stringReplace
=> logs: Removes assertion that blocks manifest generation downstream

configuration/components/loki.libsonnet, configuration/examples/base/manifests/observatorium/loki-config-map.yaml, configuration/examples/dev/manifests/observatorium/loki-config-map.yaml, configuration/examples/local/manifests/observatorium/loki-config-map.yaml
This PR adds compactor ring configuration to the compactor component in the Loki ConfigMap
Prerequisite to https://github.com/rhobs/configuration/pull/444
@periklis
=> logs: add compactor_ring

configuration/components/loki.libsonnet, configuration/examples/base/manifests/observatorium/loki-ruler-http-service.yaml, configuration/examples/dev/manifests/observatorium/loki-ruler-http-service.yaml, configuration/examples/local/manifests/observatorium/loki-ruler-http-service.yaml
Forgot ruler in PR https://github.com/observatorium/observatorium/pull/521
=> Adds old ruler http service

docs/community/maintainers.md
Following the invitation procedures.
=> Add douglascamata (me) as maintainer

configuration_go/abstr/kubernetes/thanos/compactor/compactor.go, configuration_go/abstr/kubernetes/thanos/receive/controller.go, configuration_go/abstr/kubernetes/thanos/receive/limits.go, configuration_go/abstr/kubernetes/thanos/receive/receive.go, configuration_go/abstr/kubernetes/thanos/store/store.go, configuration_go/k8sutil/k8sutil.go, configuration_go/k8sutil/providers.go, configuration_go/schemas/thanos/cache/cache.go, configuration_go/schemas/thanos/objstore/objstore.go, configuration_go/schemas/thanos/option/option.go, configuration_go/schemas/thanos/reqlogging/reqlogging.go, configuration_go/schemas/thanos/tracing/client/client.go
Adds the receive component to the Go configuration files.
=> Add receive to Go configs
