- build.sh
- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/telemeter-secret.yaml
- environments/kubernetes/manifests/telemeter-serviceMonitor.yaml
- environments/kubernetes/manifests/telemeter-serviceMonitorFederate.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet.yaml
- environments/kubernetes/telemeter.libsonnet
- environments/openshift/kube-thanos.libsonnet
- environments/openshift/main.jsonnet
- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/telemeter.libsonnet
The two files for telemeter and kube-thanos expose their own OpenShift templates:
```
environments/openshift/telemeter.libsonnet
environments/openshift/kube-thanos.libsonnet
```
Then in `environments/openshift/main.libsonnet` we just merge both Templates together.
/cc @brancz @aditya-konarde
> Add Telemeter to Openshift Templates

- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
This commit bumps the Telemeter dependency in order to incorporate a
newly added metric that tracks the cluster installation method.
cc @metalmatze @kakkoyun
> jsonnet: bump telemeter dep

- components/thanos-receive-controller.libsonnet
- environments/kubernetes/manifests/thanos-receive-controller-deployment.yaml
- environments/openshift/manifests/observatorium-template.yaml
Closes #14 
With https://github.com/observatorium/thanos-receive-controller/pull/18 merged we can now move away from using `:latest`.
> Use a unique image tag for thanos-receive-controller image

- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
This commit adds an OpenShift OAuth proxy in front of the Thanos querier for the OpenShift environment. The OpenShift route for the querier is not included here as that must be created by an admin out of bounds, just like the telemeter prometheus [0] manifests have no route.
cc @metalmatze @aditya-konarde @kakkoyun 
[0] https://github.com/openshift/telemeter/blob/master/manifests/prometheus/list.yaml
>  environments/openshift: add querier proxy

- .drone.yml
- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet.yaml
- environments/kubernetes/manifests/thanos-store-statefulSet.yaml
- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
Add basic CI for PRs (: 
The referenced commit for kube-thanos in the jsonnet lockfile does not
actually exist upstream. It seems there must have been a force push or
something that overwrote it. This bumps the commit and re-generates the
files.
cc @metalmatze
> .drone.yml: add basic CI

- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
As it seems complicated to get another ServiceAccount, let's just use telemeter-server as serviceAccount to make the SAR. 
/cc @aditya-konarde @squat @brancz
> environments/openshift: Use telemeter-server serviceAccount for Thanos querier

- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
Kind of fixes #26 by updating to use `prometheus-telemeter` ServiceAccount and ServiceAccountName.
/cc @aditya-konarde @brancz @squat
> Use proper prometheus-telemeter serviceAccount

- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/kubernetes/manifests/thanos-querier-service.yaml
- environments/kubernetes/manifests/thanos-receive-service.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet.yaml
- environments/kubernetes/manifests/thanos-store-service.yaml
- environments/kubernetes/manifests/thanos-store-statefulSet.yaml
- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
- environments/sre/servicemonitors.jsonnet
- environments/sre/servicemonitors/observatorium-thanos-querier-serviceMonitor.yaml
- environments/sre/servicemonitors/observatorium-thanos-receive-serviceMonitor.yaml
- environments/sre/servicemonitors/observatorium-thanos-store-serviceMonitor.yaml
- jsonnetfile.lock.json
This commit changes the app: ... labels on all of the resources
to the new label names specified in:
https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels.
cc @kakkoyun @metalmatze @aditya-konarde 
xref: https://github.com/metalmatze/kube-thanos/pull/20
> jsonnet: update 'app' labels

- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/thanos-receive-controller-configmap.yaml
- environments/kubernetes/manifests/thanos-receive-service-default.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml
- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
- tenants.libsonnet
Previously, only one Thanos receive StatefulSet could be created with
our config. This allows for a StatefulSet and Service to be created
per hashring as well as one Service to select them all and be used by
the querier.
cc @kakkoyun @metalmatze
> environemnts: fix services for thanos receive

- components/thanos-receive-controller.libsonnet
- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/thanos-receive-controller-deployment.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml
- environments/openshift/manifests/observatorium-template.yaml
xref https://github.com/observatorium/thanos-receive-controller/pull/21
note, for this to work, we have to make sure that the configmaps in staging and prod have the right hashring name, i.e. `default` rather than `thanos-receive-default`.
> environments: use labels for hashring names

- environments/sre/servicemonitors.jsonnet
- environments/sre/servicemonitors/observatorium-thanos-receive-production.servicemonitor.yaml
- environments/sre/servicemonitors/observatorium-thanos-receive-stage.servicemonitor.yaml
Right now, the thanos-receive ServiceMonitor selector selects
both the `thanos-receive` and `thanos-receive-default` services.
This results in doubled metrics.
Both services should exist, but only one or the other should be
selected. Each statefulset also needs its own service and
thanos-receive will select all hash rings (so telemeter can forward
to all with just one service, querier can select all etc).
This PR adds an additional selector to the ServiceMonitor to onle select
the services specific to each statefulset, excluding the overarching
service.
cc @metalmatze @brancz @aditya-konarde @kakkoyun
> environments/sre: doubled thanos-receive metrics

- environments/sre/servicemonitors.jsonnet
- environments/sre/servicemonitors/observatorium-thanos-receive-default-production.servicemonitor.yaml
- environments/sre/servicemonitors/observatorium-thanos-receive-default-stage.servicemonitor.yaml
Just as we have one service for every thanos-receive hashring, we want
one service monitor for every hashring as well.
cc @metalmatze @kakkoyun
> environments: add service monitor per tenant

- components/thanos-receive-controller.libsonnet
- environments/kubernetes/manifests/thanos-receive-controller-deployment.yaml
- environments/openshift/manifests/observatorium-template.yaml
After adding service monitors #44, we haven't able to scrape any metrics so far. I assumed `thanos-receive-controller` deployment has a missin port specification.
This PR attempts to solve the specified problem.
cc @squat @metalmatze
> Add missing container port for Thanos Receive controller

- components/thanos-querier-cache.libsonnet
- environments/kubernetes/manifests/thanos-querier-cache-configmap.yaml
- environments/kubernetes/manifests/thanos-querier-cache-service.yaml
- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
Changes: 
- Add an auth proxy container for the cache container
- Change the cache port to `9090` to be consistent with the querier. 
Related: PR for adding a route redirect reference on the SA used for the auth proxy is already created here: https://github.com/openshift/telemeter/pull/233
> Add auth proxy for cache, change cache container port

- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
Currently conflicts with the querier tls secret and causes an error
> Fix serving cert secret name for querier cache

- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
This is required because the `default` serviceaccount that gets used in the pod doesn't have the necessary permissions to create a `SubjectAccessReview`. SAR's are needed by the auth proxy
> Use prometheus-telemeter SA for querier-cache Pod

- environments/kubernetes/manifests/telemeter-statefulSet.yaml
- environments/kubernetes/telemeter.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
This commit decreases the token validity from 24h to 1hr following a
request from the tollbooth team.
cc @aditya-konarde @metalmatze @abhgupta
> environments: decrease token validity

- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
This adds whitelisting of `console_url`. Original PR -> https://github.com/openshift/telemeter/pull/239
FYI @benjaminapetersen
> Add console url

- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml
- environments/openshift/manifests/observatorium-template.yaml
This reverts commit 79ac27fdc9dc30569e18409f30230ac6c80ecdb5 or https://github.com/observatorium/configuration/pull/75 to be more precise.
> Revert "Update retention to be 32d,92d,0d"

- environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml
- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
This commit bumps the kube-thanos version to include a fix in PR
https://github.com/thanos-io/kube-thanos/pull/48. This PR fixes an issue
where saas-herder is unable to deploy the Thanos compactor due to a
detected skew in the compactor StatefulSet.
cc @kakkoyun @aditya-konarde
> jsonnetfile: bump kube-thanos to fix compactor

- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml
- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml
- environments/kubernetes/manifests/thanos-store-statefulSet.yaml
I'd like to bump Thanos version to `v0.7.0` for Observatorim to utilize new probes.
cc @brancz @bwplotka
> Bump Thanos version v0.7.0

- components/jaeger-collector.libsonnet
- environments/kubernetes/jaeger.libsonnet
- environments/kubernetes/main.jsonnet
- environments/kubernetes/manifests/jaeger-deployment.yaml
- environments/kubernetes/manifests/jaeger-headlessService.yaml
- environments/kubernetes/manifests/jaeger-queryService.yaml
- environments/kubernetes/manifests/jaeger-volumeClaim.yaml
This is a first draft to get Jaeger all in one in Observatorium. This brings a simple Jaeger setup using the `all-in-one` strategy and uses the badger storage type.
This does *not* reflect a production installation as the operator would do. Namely, I removed all the ports that might not be necessary by Thanos. I assume that it will use a Jaeger Agent as sidecar, and this sidecar will then use gRPC to talk to the collectors.
The headless service is to enable the gRPC client side load balancing to work. No services with IP are provided, as I don't think Istio (or other types of ingresses) will be necessary, but I can certainly add an IP-service if needed.
I added a `Makefile` and added a couple of lines to the readme, based on my needs as someone trying to understand how it all works. Let …
> Added jaeger all in one with badger storage

- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/openshift/manifests/observatorium-template.yaml
While this could be done at runtime as well as a query parameter, this will for now give us the correct result when querying. Note this will only really have an effect once in-cluster switches to remote write.
@metalmatze @squat @bwplotka @kakkoyun
> *: Add in-cluster prometheus_replica label for dedup.

- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
whitelist metrics and update  temeter version  for following metrics   cluster:network_attachment_definition_instances:max cluster:network_attachment_definition_enabled_instance_up:max
Continuation from
1. https://github.com/openshift/telemeter/pull/262 
2. https://github.com/openshift/cluster-monitoring-operator/pull/537
> Add network_attachment_definition for multus changes

- components/jaeger-agent.libsonnet
- environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml
- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/kubernetes/manifests/thanos-receive-controller-deployment.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml
- environments/kubernetes/manifests/thanos-store-statefulSet.yaml
- environments/openshift/kube-thanos.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/prometheus.libsonnet
- jsonnetfile.lock.json
Add missing resource requests and limits for containers that don't have that.
One final one is missing, but that's not defined in this repo, but rather a dependency. For that I've created: https://github.com/observatorium/thanos-receive-controller/pull/35
> Add resource requests and limits to containers without

- components/jaeger-agent.libsonnet
- components/jaeger-collector.libsonnet
- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/jaeger-adminService.yaml
- environments/kubernetes/manifests/jaeger-agentService.yaml
- environments/kubernetes/manifests/jaeger-deployment.yaml
- environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml
- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml
- environments/kubernetes/manifests/thanos-store-statefulSet.yaml
- environments/openshift/manifests/jaeger-template.yaml
- environments/openshift/manifests/observatorium-template.yaml
- environments/sre/servicemonitors.jsonnet
- environments/sre/servicemonitors/observatorium-jaeger-agent-stage.servicemonitor.yaml
- environments/sre/servicemonitors/observatorium-jaeger-agent.servicemonitor.yaml
- environments/sre/servicemonitors/observatorium-jaeger-stage.podmonitor.yaml
- environments/sre/servicemonitors/observatorium-jaeger.podmonitor.yaml
This PR attempts to fix issues with monitoring jaeger components.
* Adds a new admin service for jaeger collector. (https://www.jaegertracing.io/docs/1.15/monitoring/)
* Fixes `ServiceMonitor` to point correct service.
* ~~Adds a `PodMonitor` to monitor `jaeger-agent`s~~
* Adds a `ServiceMonitor` to select and monitor `jaeger-agent`s
(https://www.jaegertracing.io/docs/1.15/deployment/#agent)
* Adds liveness probes for `jaeger-agent`s (https://github.com/jaegertracing/jaeger/blob/master/pkg/healthcheck/handler.go)
> Fix Jaeger component monitoring issues

- components/jaeger-collector.libsonnet
- environments/kubernetes/manifests/jaeger-agentService.yaml
- environments/openshift/manifests/jaeger-template.yaml
This PR fixes the issue caused by the name of the service.
A similar issue could be found https://github.com/grafana/loki/issues/480
> Rename Jaeger Agent service

- components/jaeger-agent.libsonnet
- environments/kubernetes/manifests/thanos-compactor-statefulSet.yaml
- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml
- environments/kubernetes/manifests/thanos-store-statefulSet.yaml
- environments/openshift/manifests/observatorium-template.yaml
This PR increases the memory limits of jaeger-agents.
jaeger-agent, by default, allocates a queue to store spans before it sends it to the collector.
> Each queue is 1000 span batches. Given that each span batch has up to 64KiB worth of spans, each queue can hold up to 64MiB worth of span.
Normally this queue is mostly empty but when the collector is down it quickly reaches saturation. In our setup we have a limit of `64MiB` and it needs slightly more than that, so it gets OOMkilled.
ref: https://www.jaegertracing.io/docs/1.15/performance-tuning/#adjust-server-queue-sizes
cc @aditya-konarde @brancz @bwplotka
> Increase jaeger agent memory limit

- components/thanos-querier-cache.libsonnet
- environments/kubernetes/manifests/thanos-querier-cache-deployment.yaml
- environments/openshift/manifests/observatorium-template.yaml
We don't have Kubernetes 1.13+ yet... :cry: 
This reverts commit ebf189d8280f2f852c1d07ec9fd4c0e153e13e7c.
> Revert "Disable ServiceLinks for Cortex cache"

- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
jsonnetfile: Bump to newer telemeter for cluster:usage:*
> Bug 1779912: Add a whitelist cluster:usage:* for telemetry for simple usage metric exposure

- environments/kubernetes/main.jsonnet
- environments/kubernetes/manifests/telemeter-memcached-service.yaml
- environments/kubernetes/manifests/telemeter-memcached-statefulSet.yaml
- environments/kubernetes/manifests/telemeter-statefulSet.yaml
- environments/kubernetes/telemeter.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/manifests/telemeter-template.yaml
- environments/openshift/telemeter.jsonnet
- jsonnetfile.lock.json
This commit adds a Memcached StatefulSet with one replica to the
Telemeter OpenShift template and configures telemeter-server to use it
for caching authentication responses to requests made to the
remote-write endpoint. Before merging this, we need to bump the
telemeter-server image tag to include the caching code.
cc @metalmatze @kakkoyun @brancz @bwplotka @aditya-konarde
> environments: add memcached to telemeter

- environments/kubernetes/manifests/telemeter-memcached-statefulSet.yaml
- environments/kubernetes/telemeter.libsonnet
- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/manifests/telemeter-template.yaml
- environments/openshift/telemeter.jsonnet
This commit adds resource requests and limits to the Memcached exporter
container, as required by CI.
cc @kakkoyun @brancz @metalmatze @aditya-konarde
> environments: resource requests/limits on exporter

- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/thanos-receive-statefulSet-default.yaml
- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/manifests/thanos-template.yaml
This commit enables replication of all received data. It ensures that
all hashrings with more than 3 replicas will have a replication factor
of 3.
cc @kakkoyun @metalmatze @aditya-konarde 
We need to discuss if increased CPU + disk usage to handle replication
will be provisioned.
> environment/kubernetes: replicate received data

- environments/kubernetes/kube-thanos.libsonnet
- environments/kubernetes/manifests/thanos-querier-deployment.yaml
- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/manifests/thanos-template.yaml
As we override the args for the Thanos Querier entirely, we simply need to add the flag as is.
/cc @aditya-konarde @squat
> Add replica-label=ruler_replica to querier for dedup

- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
Updates to latest kube-thanos to ensure that the hashring config volume is correctly set.
@metalmatze @squat @bwplotka @krasi-georgiev @kakkoyun
> environments/openshift: Fix hashring config mount

- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/obs.jsonnet
Removing for now as we're still testing this on stage with the obs API but we can't promote this to prod without the API which we're not intending to do yet.
@squat @metalmatze @kakkoyun @bwplotka @krasi-georgiev
> environments/openshift: Remove web external prefix

- environments/openshift/jaeger.jsonnet
- environments/openshift/manifests/jaeger-template.yaml
- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/obs.jsonnet
OSDv4 doesn't have a storageclass called `gp2-encrypted` but instead has `gp2`. Changing this in advance so that we don't fail on first deploy :)
> WIP: Change storageclass on OpenShift manifests to gp2

- environments/openshift/manifests/observatorium-template.yaml
- environments/openshift/obs.jsonnet
This commit is a follow up from previous incidents. It puts the Thanos
receiver in the QoS class. This will also give yield more consistent
scaling characteristics once we introduce HPA.
This is a follow up from our last incident.
cc @metalmatze @brancz @kakkoyun
> openshift: thanos receive guaranteed QoS

- components/jaeger-collector.libsonnet
- environments/openshift/manifests/jaeger-template.yaml
By default the retention is 72h, which at consistent load explodes with
the 50G disk.
https://www.jaegertracing.io/docs/1.17/cli/#jaeger-all-in-one-badger
@squat @metalmatze @bwplotka @krasi-georgiev @aditya-konarde
> components/jaeger: Reduce retention to 3h

- environments/openshift/jaeger.jsonnet
- environments/openshift/manifests/jaeger-template.yaml
Let's parameterize Jaeger so we can more quickly update the requests and limits (with the current deployment approach)
/cc @observatorium/maintainers @aditya-konarde
> Parameterize the Jaeger resource requests and limits

- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
This commit bumps the Telemeter dependency to remove the gossip flags
from the configuration. It also has the side effect of eliminating the
prometheus-operator jsonnet dependency :)
cc @brancz @aditya-konarde @metalmatze
> jsonnet: bump telemeter to remove gossip

- components/cortex-query-frontend.libsonnet
- environments/base/manifests/query-cache-deployment.yaml
- environments/dev/manifests/query-cache-deployment.yaml
- environments/openshift/manifests/observatorium-template.yaml
Debug logging enables logging of trace ID, which will help us understand
failing queries.
@metalmatze @squat @aditya-konarde
> *: Query cache debug logging

- components/cortex-query-frontend.libsonnet
- environments/base/manifests/query-cache-deployment.yaml
- environments/dev/manifests/query-cache-deployment.yaml
- environments/openshift/manifests/observatorium-template.yaml
This configures various timeouts in the system to be 15min by default.
@bwplotka @metalmatze @squat @krasi-georgiev @kakkoyun
> cortex-query-frontend: Adjust various querying timeouts

- deploy/operator.yaml
- tests/e2e.sh
The current test is pulling the latest image from quay, so it is not testing the changes introduced in PRs.
With this change, an image is build based on the PR and loaded in the cluster using `kind load docker-image`.
> Test operator with image build on PR

- components/observatorium.libsonnet
- environments/base/manifests/thanos-compact-statefulSet.yaml
- environments/base/manifests/thanos-store-shard0-statefulSet.yaml
- environments/dev/manifests/thanos-compact-statefulSet.yaml
- environments/dev/manifests/thanos-store-shard0-statefulSet.yaml
- environments/openshift/manifests/observatorium-template.yaml
- jsonnetfile.lock.json
This PR depends on the latest version of Thanos and kube-thanos.
Depends: https://github.com/observatorium/configuration/pull/222
xref: https://github.com/thanos-io/kube-thanos/pull/105
About flags:
```
--delete-delay=48h
Time before a block marked for deletion is deleted from bucket.
If delete-delay is non zero, blocks will be marked for deletion 
and compactor component will delete blocks marked for deletion from the bucket.
If delete-delay is 0, blocks will be deleted straight away.
Use this if you want to get rid of or move the block immediately.
Note that deleting blocks immediately can cause query failures, 
if store gateway still has the block loaded, or compactor is ignoring the deletion 
because it's compacting the block at the same time.
```
```
--ignore-deletion-marks-delay=24h …
```
> Enable offline deduplication

- Makefile
- go.mod
- go.sum
This patch will also add a Makefile entry to better handle go vendoring
Fixes: #232
> Fix go module path to include observatorium/configuration

- components/jaeger-collector.libsonnet
- environments/openshift/jaeger.jsonnet
- environments/openshift/manifests/jaeger-template.yaml
This commit reconfigures Jaeger to use its in-memory store rather than
Badger, due to performance and operational issues we have been having in
production. Note that unlike Badger, the in-memory store does not
support time-based retention; instead it only supports limiting the
total number of traces. This limit is parameterized as an OpenShift
template variable.
cc @brancz @metalmatze @jpkrohling 
PS: is 100k a sane limit? Or is this too high/will this require too much memory?
> components/jaeger-collector: move to memory store

- environments/openshift/jaeger.jsonnet
- environments/openshift/manifests/jaeger-template.yaml
This commit fixes the `--memory.max-traces` flag on the Jaeger
deployment.
> environments/openshift: fix jaeger flag

- .circleci/config.yml
This commit de-duplicated the CircleCI configuration so that the build
and test jobs are not run twice for every single PR.
> .circleci: simplify config

- example/main.jsonnet
- example/manifests/observatorium.yaml
The following keys in the metadata are currently ignored:
app.kubernetes.io/component
app.kubernetes.io/instance
app.kubernetes.io/name
app.kubernetes.io/part-of
this PR moves them to metadata.labels
> Set labels properly on the sample CR

- components/up.libsonnet
- environments/dev/main.jsonnet
- environments/dev/manifests/up-deployment.yaml
This should be easier to configure and the --endpoint-read and --endpoint-write are added as flags, simply by not having `''` in the config.
/cc @kakkoyun @brancz
> Remove withXXX helper functions from up component

- tests/e2e.sh
Currently, the e2e.sh tests script downloads both kind
and kubctl binaries for Linux.
Developers (myself included) might want to test locally,
and this will not work correctly under macOS (Darwin).
This patch will improve e2e.sh and allow it to download
the binaries that match the operating system.
> Adapt tests script for macOS

- components/up.libsonnet
- environments/dev/manifests/up-deployment.yaml
The queries-file flag should be provided only when present in the config.
fixes https://github.com/observatorium/configuration/issues/285
cc @metalmatze , @brancz 
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>
> queries-file container flag bug

- components/observatorium.libsonnet
- environments/base/manifests/thanos-receive-default-statefulSet.yaml
- environments/dev/manifests/thanos-receive-default-statefulSet.yaml
4 days is enough to bridge a weekend if necessary, but also limits the
disk space needed by each receive node.
@observatorium/maintainers
> receive: Reduce retention to 4 days

- README.md
This commit fixes the links in the README to reflect the new project
URL and adds some more details to the description.
cc @observatorium/maintainers  @nmagnezi
> README: update links and description

- doc/operator/deploy-operator.md
- environments/dev/main.jsonnet
- environments/dev/manifests/minio-deployment.yaml
- environments/dev/manifests/minio-pvc.yaml
- environments/dev/manifests/minio-secret.yaml
- environments/dev/manifests/minio-service.yaml
- tests/e2e.sh
While deploying Observatorium to an actual cluster, I find it quite weird to have a random minio namespace, I'd rather prefix it with Observatorium, to make it more obvious to others.
/cc @kakkoyun @squat @rollandf
> Rename minio namespace to observatorium-minio

- components/observatorium.libsonnet
- environments/base/manifests/thanos-query-deployment.yaml
- environments/dev/manifests/thanos-query-deployment.yaml
Thanks to thanos-io/thanos#2714, all links in
the frontend are now relative. Unfortunately, that means that using
`--external-prefix=.` turns `static/x` into `.static/x`, which doesn't
exist. We'll fix this here now and then ensure we sanitize this upstream
in Thanos.
cc @observatorium/maintainers
> Fix external prefix

- doc/operator/deploy-operator.md
Documentation still references old path in one of the manifest list blocks. Update to point at new repository.
> Fix path to manifests

- components/loki.libsonnet
- environments/base/manifests/loki-ingester-http-service.yaml
- environments/dev/manifests/loki-ingester-http-service.yaml
This PR enables per default the HTTP svc for Loki's ingester component. By this prometheus can scrape this endpoint for metrics.
> Enable metrics svc for loki ingester component

- tests/e2e.sh
Previously, trying to run must-gather for initcontainers would return
incorrect logs. This commit fixes the function.
cc @observatorium/maintainers
> tests/e2e.sh: fix must-gather for initcontainers

- components/loki-caches.libsonnet
- components/loki.libsonnet
This PR addresses the missing service monitors for the loki caches as well as allows overriding loki's service monitor manifest for additional labels and selectors.
> Add service monitor config for loki and lokiCaches

- components/loki.libsonnet
This PR addresses a small issue with ServiceMonitor matching labels for loki components.
> Fix loki service monitor labels

- components/loki.libsonnet
- components/observatorium.libsonnet
This PR addresses a set of hindsights on optional functionality post-introduction of statefulsets for ingesters and queriers. The optional `with{Replicas,Requests,ServiceMonitors}` remain unused in this repository, thus it was an easy mistake ;)
> Fix with{Replicas,Requests,ServiceMonitors} for statefulsets

- .circleci/config.yml
This hasn't been spotted until we merged the latest PR into master. We don't have any containers to push from this repository anymore and thus builds on master are broken.
> Remove container-push job from CircleCI

- components/observatorium.libsonnet
There is an error without loki in CR
```
level=warn ts=2020-09-16T06:37:43.908034Z caller=resource.go:167 msg="sync failed" key=default/observatorium-xyz err="failed to render: failed to evaluate: RUNTIME ERROR: Field does not exist: replicas\n\tvendor/github.com/observatorium/deployments/components/observatorium.libsonnet:280:19-38\tobject <anonymous>\n\tvendor/github.com/observatorium/deployments/components/loki.libsonnet:420:36-53\tthunk from <object <anonymous>>\n\t<std>:1278:24-25\tthunk from <function <anonymous>>\n\t<std>:1278:5-33\tfunction <anonymous>\n\tvendor/github.com/observatorium/deployments/components/loki.libsonnet:420:19-54\tobject <anonymous>\n\t\t\n\t\t\n\tvendor/github.com/observatorium/deployments/components/observatorium.libsonnet:329:34-52\tthunk from <object …
```
> Make loki optional

- .bingo/Variables.mk
- Makefile
```console
Makefile:28: warning: overriding commands for target `/Users/kakkoyun/Sandbox/deployments/tmp/bin/generate-tls-cert'
.bingo/Variables.mk:51: warning: ignoring old commands for target `/Users/kakkoyun/Sandbox/deployments/tmp/bin/generate-tls-cert'
```
> Fix Make warnings

- components/loki.libsonnet
- environments/base/default-config.libsonnet
- environments/base/manifests/loki-config-map.yaml
- environments/base/manifests/loki-distributor-deployment.yaml
- environments/base/manifests/loki-distributor-grpc-service.yaml
- environments/base/manifests/loki-distributor-http-service.yaml
- environments/base/manifests/loki-gossip-ring.yaml
- environments/base/manifests/loki-ingester-grpc-service.yaml
- environments/base/manifests/loki-ingester-http-service.yaml
- environments/base/manifests/loki-ingester-statefulset.yaml
- environments/base/manifests/loki-querier-grpc-service.yaml
- environments/base/manifests/loki-querier-http-service.yaml
- environments/base/manifests/loki-querier-statefulset.yaml
- environments/base/manifests/loki-query-frontend-deployment.yaml
- environments/base/manifests/loki-query-frontend-grpc-service.yaml
- environments/base/manifests/loki-query-frontend-http-service.yaml
- environments/dev/manifests/loki-config-map.yaml
- environments/dev/manifests/loki-distributor-deployment.yaml
- environments/dev/manifests/loki-distributor-grpc-service.yaml
- environments/dev/manifests/loki-distributor-http-service.yaml
- environments/dev/manifests/loki-gossip-ring.yaml
- environments/dev/manifests/loki-ingester-grpc-service.yaml
- environments/dev/manifests/loki-ingester-http-service.yaml
- environments/dev/manifests/loki-ingester-statefulset.yaml
- environments/dev/manifests/loki-querier-grpc-service.yaml
- environments/dev/manifests/loki-querier-http-service.yaml
- environments/dev/manifests/loki-querier-statefulset.yaml
- environments/dev/manifests/loki-query-frontend-deployment.yaml
- environments/dev/manifests/loki-query-frontend-grpc-service.yaml
- environments/dev/manifests/loki-query-frontend-http-service.yaml
This is a minor PR with major impact as it is addressing the bump of Loki from 1.6.1 to 2.0.0. Major points addressed by upstream regarding boltdb-shipper:
- https://github.com/grafana/loki/pull/2770
- https://github.com/grafana/loki/pull/2601
> Bump loki 1.6.1 to 2.0.0

- components/loki.libsonnet
- environments/base/manifests/loki-compactor-http-service.yaml
- environments/dev/manifests/loki-compactor-http-service.yaml
This PR addresses the missing k8s svc resource to enable scraping the Loki compactor component metrics.
> Add svc for loki compactor metrics

- environments/base/default-config.libsonnet
- environments/base/manifests/api-deployment.yaml
- environments/base/manifests/api-service.yaml
- environments/base/manifests/api-serviceAccount.yaml
- environments/dev/manifests/api-configmap.yaml
- environments/dev/manifests/api-deployment.yaml
- environments/dev/manifests/api-secret.yaml
- environments/dev/manifests/api-service.yaml
- environments/dev/manifests/api-serviceAccount.yaml
- tests/main.jsonnet
- tests/manifests/observatorium-up-logs.yaml
This PR bumps the API version to include the following fixes:
https://github.com/observatorium/observatorium/compare/76a4c28...e32405763b667866022ca84af5c4c34ffea7700e
> Bump api v0.1.1-187-g76a4c28 to v0.1.1-192-ge324057

- components/loki.libsonnet
- components/observatorium.libsonnet
- environments/base/manifests/loki-compactor-statefulset.yaml
- environments/base/manifests/loki-config-map.yaml
- environments/base/manifests/loki-distributor-deployment.yaml
- environments/base/manifests/loki-ingester-statefulset.yaml
- environments/base/manifests/loki-querier-statefulset.yaml
- environments/base/manifests/loki-query-frontend-deployment.yaml
- environments/dev/manifests/loki-compactor-statefulset.yaml
- environments/dev/manifests/loki-config-map.yaml
- environments/dev/manifests/loki-distributor-deployment.yaml
- environments/dev/manifests/loki-ingester-statefulset.yaml
- environments/dev/manifests/loki-querier-statefulset.yaml
- environments/dev/manifests/loki-query-frontend-deployment.yaml
This PR exposes the `replication_factor` configuration option via `withReplicationFactor`. This way it enables overrides via OpenShift template parameters. Later cannot be replaced inside config map data blocks. Thus, the present implementation provides an override via container parameters.
> [loki] Add withDataReplication to enable replication config

- components/loki.libsonnet
This PR remove obsolete asserts in the `withConfig` to allow composability with other loki `with*` functions.
> [loki] Remove obsolete asserts from withConfig

- components/memcached.libsonnet
- components/observatorium.libsonnet
- components/thanos.libsonnet
- jsonnetfile.json
- jsonnetfile.lock.json
This exposes some more configurability for the thanos component. As you can see (by `make generate` not causing anything to change), this does not change any of the output, it's just a refactoring exposing these configuration options. It also updates and changes kube-thanos "version" from "master" to "main".
As a side note, this "thanos" component is now so generic, it should probably be in kube-thanos.
@kakkoyun
> Extend configurability and update kube-thanos

- components/thanos.libsonnet
This allows piping through configuration to the kube-thanos receive component without having to manually pipe it through here.
@kakkoyun
> thanos: Allow piping through receive config

- tests/main.jsonnet
- tests/manifests/observatorium-up-logs-tls.yaml
- tests/manifests/observatorium-up-logs.yaml
- tests/manifests/observatorium-up-metrics-tls.yaml
- tests/manifests/observatorium-up-metrics.yaml
If a Container specifies its own CPU limit, but does not specify a CPU request, Kubernetes automatically assigns a CPU request that matches the limit. Set requests for up smaller than limit to ensure the tests can be passed in https://github.com/observatorium/operator/pull/52.
Signed-off-by: clyang82 <chuyang@redhat.com>
> Set requests for up test

- website/config/_default/menus.toml
- website/layouts/index.html
This commit fixes links in the website that are pointing to the
non-existant architecture/architecture path. It also removes this
section, which is currently empty, from the sidebar. Finally, it changes
the default docs and getting-started links to the getting-started.md
page.
> website: fix 404 links to architecture

- configuration/components/minio.libsonnet
- configuration/examples/dev/main.jsonnet
- configuration/examples/dev/manifests/minio-deployment.yaml
- configuration/examples/local/main.jsonnet
- configuration/examples/local/manifests/minio-deployment.yaml
I'd like to reuse the minio component for something unrelated to thanos and loki. Regardless I think it didn't make sense for the secrets that are specific to thanos and loki to leak into the minio component. A next step might be to pass the secrets into the thanos/loki components, however, I didn't want to do that as I think that might be too opinionated, as many people prefer configuring secrets via vault or some other custom volume that is not necessarily a Kubernetes secret, so I didn't want to force one opinion or the other even stronger than we already are.
@kakkoyun @metalmatze @onprem @periklis
> components: Decouple thanos & loki secrets from minio

- configuration/jsonnetfile.json
- configuration/jsonnetfile.lock.json
This commit bumps the jb dependency files to use the new default branch
name for the observatorium/api repository.
xref: https://github.com/observatorium/api/pull/147
> configuration: rename obs/api default branch

- docs/proposals/_index.md
- docs/proposals/drafts/20210709-opa-authorizer-labels-observatorium-api.md
- docs/proposals/drafts/_index.md
- website/config/_default/menus.toml
The following design proposal provide an extension for the observatorium api to OPA authorizers. In particular this extension addresses the issue to refine queries to read endpoints with label matchers provided by the OPA authorizer. It is inspired by the work on tenant isolation. Although it goes one step further to handle dynamic label matchers provided by domain specific OPA authorizers in form of PromQL's `labels.Matcher` (See [prometheus/pkg/labels/matcher.go](https://github.com/prometheus/prometheus/blob/main/pkg/labels/matcher.go#L45)).
> Add Authz Matchers API proposal

- configuration/components/minio.libsonnet
- configuration/examples/dev/manifests/minio-deployment.yaml
- configuration/examples/local/manifests/minio-deployment.yaml
While trying to spin up Observatorium in a local k8s cluster, I got this error after trying to deploy `minio`:
```bash
jessica@pop-os:~/workspace/observatorium/configuration/examples/local|main ⇒  kubectl get pods
NAME                     READY   STATUS             RESTARTS   AGE
minio-77f7856ddc-95zfm   0/1     CrashLoopBackOff   10         31m
jessica@pop-os:~/workspace/observatorium/configuration/examples/local|main ⇒  kubectl logs minio-77f7856ddc-95zfm
/bin/sh: line 1: /usr/bin/minio: No such file or directory
```
After some investigation with @ianbillett and following https://gitmemory.cn/repo/minio/minio/issues/13181, we've updated the command accordingly and also pinned the image to latest [release](https://github.com/minio/minio/releases/tag/RELEASE.2021-09-09T21-37-07Z).
We've …
> Minio: Fix local/dev deployments, fix libsonnet

- Makefile
This PR fixes broken `web` & `web-serve` targets in Makefile as mentioned in #430 & #428.
> Fix web targets in Makefile

- docs/usage/getting-started.md
If you are using Kind with Docker Desktop on Mac, there is no `docker0` IP interface accessible on the host; this is because Docker-for-mac [containers run via a Virtual Machine (HyperKit)](https://docs.docker.com/desktop/mac/install/). As a workaround, Docker provides a special DNS entry [`host.docker.internal`](https://docs.docker.com/desktop/mac/networking/#use-cases-and-workarounds).
I've updated the docs with this detail to allow MacOS users to run Observatorium locally without issue, i've also added macos CDN links for prom and hydra too.
> Updating the local getting-started.md docs for MacOS compatibility

- docs/proposals/20201123-tracing-ingestion-api-and-opentelemetry-collector.md
This proposal bootstraps ingestion of tracing data in Observatorium.
The second proposal will build on top of this and add traicng
platform/storage.
Updates: #442 
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>
> Add proposal to add tracing ingestion API and OpenTelemtry collector

- docs/proposals/drafts/20211007-pluggable-authenticators.md
Propose refactoring the current authenticators setup to provide
pluggable based approach to make it flexible to onboard custom
authentication, this proposal would help new adopters to onboard
their authenticators.
> Propose a new pluggable authenticators

- docs/proposals/drafts/20211007-pluggable-authenticators.md
- docs/proposals/drafts/20211106-plugable-authorizers.md
Propose refactoring the current authorization providers setup to provide
pluggable based approach to make it flexible to onboard custom
authorization, this proposal would help new adopters to onboard
their custom authorization implementation.
Signed-off-by: Neyyan Sony <neyysony@in.ibm.com>
> Pluggable authorizers proposal

- docs/design/rules-api.md
- Adds documentation about the recently implemented Rules API
- Would it be useful to add also an architecture diagram and mention `rules-objstore`? Or we would prefer to keep it simple and just mention how a tenant can interact with the API?
> Rules API: Add docs

- configuration/components/loki.libsonnet
- configuration/components/observatorium.libsonnet
- configuration/examples/base/manifests/loki-config-map.yaml
- configuration/examples/base/manifests/loki-index-gateway-grpc-service.yaml
- configuration/examples/base/manifests/loki-index-gateway-http-service.yaml
- configuration/examples/base/manifests/loki-index-gateway-statefulset.yaml
- configuration/examples/base/manifests/loki-querier-deployment.yaml
- configuration/examples/base/manifests/loki-query-scheduler-deployment.yaml
- configuration/examples/base/manifests/loki-query-scheduler-grpc-service.yaml
- configuration/examples/base/manifests/loki-query-scheduler-http-service.yaml
- configuration/examples/dev/main.jsonnet
- configuration/examples/dev/manifests/loki-config-map.yaml
- configuration/examples/dev/manifests/loki-index-gateway-grpc-service.yaml
- configuration/examples/dev/manifests/loki-index-gateway-http-service.yaml
- configuration/examples/dev/manifests/loki-index-gateway-statefulset.yaml
- configuration/examples/dev/manifests/loki-querier-deployment.yaml
- configuration/examples/dev/manifests/loki-query-scheduler-deployment.yaml
- configuration/examples/dev/manifests/loki-query-scheduler-grpc-service.yaml
- configuration/examples/dev/manifests/loki-query-scheduler-http-service.yaml
- configuration/examples/local/manifests/loki-config-map.yaml
- configuration/examples/local/manifests/loki-index-gateway-grpc-service.yaml
- configuration/examples/local/manifests/loki-index-gateway-http-service.yaml
- configuration/examples/local/manifests/loki-index-gateway-statefulset.yaml
- configuration/examples/local/manifests/loki-querier-deployment.yaml
- configuration/examples/local/manifests/loki-query-scheduler-deployment.yaml
- configuration/examples/local/manifests/loki-query-scheduler-grpc-service.yaml
- configuration/examples/local/manifests/loki-query-scheduler-http-service.yaml
- configuration/examples/local/quickstart.sh
- configuration/tests/e2e.sh
The following PR adds two new Loki components namely the `query-scheduler` and the `index-gateway`. The rational having this two components is:
1. The `index-gateway` incorporates loading and caching the `boltdb` index files on a persistent volume that used to live in the `querier` components. In turn queriers can be transformed from `StatefulSet` to a `Deployment` enabling horizontal scaling w/o requiring any persistent volumes anymore.
2. The `query-scheduler` incorporates the scheduling logic of multi-tenant and time-range shardable queries that used to live in the `query-frontend` and `querier` components. In turn both `query-frontend` and `querier` can be scaled horizontally without tuning the concurrency settings (e.g. `max_concurrent`). These settings will be tuned by the querier …
> loki: Add query scheduler and index gateway components

- configuration/components/loki.libsonnet
This PR adds the missing service monitor support for the loki query-scheduler and index-gateway components. Missed to add in #463
> loki: Add service monitors for query_scheduler and index_gateway

- configuration/components/observatorium.libsonnet
This PR fixes an issue where importing latest `observatorium.libsonnet` causes errors like 
```
RUNTIME ERROR: Unexpected type null, expected object
vendor/github.com/observatorium/observatorium/configuration/components/observatorium.libsonnet:(145:5)-(162:14)	object <anonymous>
services/observatorium-template.jsonnet:11:36-49	thunk from <object <anonymous>>
<std>:1293:24-25	thunk from <function <anonymous>>
<std>:1293:5-33	function <anonymous>
services/observatorium-template.jsonnet:11:19-50	object <anonymous>
services/observatorium-template.jsonnet:(7:5)-(15:6)	
During manifestation	
```
This is due to if-else blocks not being evaluated correctly, in `manifests` field.
> Fix optional manifests

- .mdox.validate.yaml
- docs/proposals/20220215-obsctl.md
This PR adds a proposal that talks about `obsctl` which is a dedicated CLI to interact with Observatorium instances.
cc: @onprem
> Add proposal for `obsctl`

- README.md
- configuration/Makefile
- configuration/README.md
Resolves https://github.com/observatorium/observatorium/issues/470
macOS includes a BSD-derived `xargs`, with very different flags from the GNU `xargs` on Linux systems.
See: https://www.freebsd.org/cgi/man.cgi?xargs
> macOS compatibility

- .mdox.validate.yaml
- docs/community/governance.md
The current Twitter link points to a non-Observatorium-related Twitter user.
> Repoint Twitter link

- docs/api.html
- website/config/_default/menus.toml
This PR adds an API documentation page for Observatorium using [redocly](https://redocly.com/).
> Add redoc for OpenAPI spec based documentation

- configuration/components/loki.libsonnet
- configuration/examples/base/manifests/observatorium/loki-ruler-statefulset.yaml
- configuration/examples/dev/manifests/observatorium/loki-ruler-statefulset.yaml
- configuration/examples/local/manifests/observatorium/loki-ruler-statefulset.yaml
This is a follow-up on #500 to remove static rules from a ConfigMap when the Loki Ruler config is using object storage as the default storage config.
> Remove volumes for loki ruler when using s3 storage

- configuration/components/loki.libsonnet
- configuration/examples/base/manifests/observatorium/loki-compactor-statefulset.yaml
- configuration/examples/base/manifests/observatorium/loki-config-map.yaml
- configuration/examples/base/manifests/observatorium/loki-distributor-deployment.yaml
- configuration/examples/base/manifests/observatorium/loki-index-gateway-statefulset.yaml
- configuration/examples/base/manifests/observatorium/loki-ingester-statefulset.yaml
- configuration/examples/base/manifests/observatorium/loki-querier-deployment.yaml
- configuration/examples/base/manifests/observatorium/loki-query-frontend-deployment.yaml
- configuration/examples/base/manifests/observatorium/loki-query-scheduler-deployment.yaml
- configuration/examples/base/manifests/observatorium/loki-ruler-statefulset.yaml
- configuration/examples/dev/manifests/observatorium/loki-compactor-statefulset.yaml
- configuration/examples/dev/manifests/observatorium/loki-config-map.yaml
- configuration/examples/dev/manifests/observatorium/loki-distributor-deployment.yaml
- configuration/examples/dev/manifests/observatorium/loki-index-gateway-statefulset.yaml
- configuration/examples/dev/manifests/observatorium/loki-ingester-statefulset.yaml
- configuration/examples/dev/manifests/observatorium/loki-querier-deployment.yaml
- configuration/examples/dev/manifests/observatorium/loki-query-frontend-deployment.yaml
- configuration/examples/dev/manifests/observatorium/loki-query-scheduler-deployment.yaml
- configuration/examples/dev/manifests/observatorium/loki-ruler-statefulset.yaml
- configuration/examples/local/manifests/observatorium/loki-compactor-statefulset.yaml
- configuration/examples/local/manifests/observatorium/loki-config-map.yaml
- configuration/examples/local/manifests/observatorium/loki-distributor-deployment.yaml
- configuration/examples/local/manifests/observatorium/loki-index-gateway-statefulset.yaml
- configuration/examples/local/manifests/observatorium/loki-ingester-statefulset.yaml
- configuration/examples/local/manifests/observatorium/loki-querier-deployment.yaml
- configuration/examples/local/manifests/observatorium/loki-query-frontend-deployment.yaml
- configuration/examples/local/manifests/observatorium/loki-query-scheduler-deployment.yaml
- configuration/examples/local/manifests/observatorium/loki-ruler-statefulset.yaml
Issue: https://issues.redhat.com/browse/LOG-3902
Moves some loki configuration that previously was being passed by CLI arguments to the loki config directly in the form of ENV vars that will then be expanded to their actual values. We need this because upstream we will want to update these values without having to regenerate the templates. Furthermore, some of the values are secrets and are only known at rollout time
> logs: moves some loki CLI args to the config

- docs/community/maintainers.md
As per mailing list announcement.
> Remove Matthias Loibl (metalmatze) as maintainer

- configuration_go/abstr/kubernetes/memcached/memcached.go
- configuration_go/abstr/kubernetes/observatoriumapi/api.go
- configuration_go/abstr/kubernetes/thanos/compactor/compactor.go
- configuration_go/abstr/kubernetes/thanos/query/query.go
- configuration_go/abstr/kubernetes/thanos/receive/controller.go
- configuration_go/abstr/kubernetes/thanos/receive/receive.go
- configuration_go/abstr/kubernetes/thanos/store/store.go
- configuration_go/k8sutil/genericdeployment.go
- configuration_go/k8sutil/providers.go
- configuration_go/k8sutil/utils.go
- configuration_go/schemas/thanos/cache/cache.go
- configuration_go/schemas/thanos/cache/memcached/memcached.go
- configuration_go/schemas/thanos/cache/memory/memory.go
- configuration_go/schemas/thanos/cache/redis/redis.go
* Adds memcached deployments
* Sets optional k8s objects as pointers to avoid empty objects generation that causes validation issues (pod affinity, container probes, security cfg)
> Go configs: Add memcached deployment and bucket cache config

- .mdox.validate.yaml
- configuration_go/abstr/kubernetes/thanos/ruler/syncer.go
The Tenants config struct being in the main package of the syncer, I cannot import it 🤦 . So I am redeclaring it here. That's not a big issue as it is a basic struct for now. Next dev in the syncer, we should move this config into its own sub-package.
> Go-config: add tenants-file option to rules syncer
